name: Build Customer App

on:
  push:
    branches:
      - main
    paths:
      - "customer_app/**"

  workflow_dispatch:

jobs:
  build-customer:
    name: Build Customer APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare Customer App
        working-directory: customer_app
        run: flutter create --platforms=android --project-name=mada_pay_customer .

      - name: Get Customer Dependencies
        working-directory: customer_app
        run: flutter pub get

      - name: Build Customer APK
        working-directory: customer_app
        run: flutter build apk --release

      - name: Upload Customer APK
        uses: actions/upload-artifact@v4
        with:
          name: mada-pay-customer-apk
          path: customer_app/build/app/outputs/flutter-apk/app-release.apk
